version: 2.1
jobs:
  build:
    docker:
      - image: circleci/hashicorp-terraform:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Setup Terraform
          command: |
            terraform --version
            terraform init

      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan

      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve tfplan

workflows:
  version: 2
  build:
    jobs:
      - build
